/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a org.bluez.Profile1 org.bluez.Profile1.xml
 *
 * qdbusxml2cpp is Copyright (C) 2019 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "org.bluez.Profile1.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class Profile1Adaptor
 */

Profile1Adaptor::Profile1Adaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

Profile1Adaptor::~Profile1Adaptor()
{
    // destructor
}

void Profile1Adaptor::Cancel()
{
    // handle method call org.bluez.Profile1.Cancel
    QMetaObject::invokeMethod(parent(), "Cancel");
}

void Profile1Adaptor::NewConnection(const QDBusObjectPath &device, const QDBusUnixFileDescriptor &fd, const QVariantMap &fd_properties)
{
    // handle method call org.bluez.Profile1.NewConnection
    QMetaObject::invokeMethod(parent(), "NewConnection", Q_ARG(QDBusObjectPath, device), Q_ARG(QDBusUnixFileDescriptor, fd), Q_ARG(QVariantMap, fd_properties));
}

void Profile1Adaptor::Release()
{
    // handle method call org.bluez.Profile1.Release
    QMetaObject::invokeMethod(parent(), "Release");
}

void Profile1Adaptor::RequestDisconnection(const QDBusObjectPath &device)
{
    // handle method call org.bluez.Profile1.RequestDisconnection
    QMetaObject::invokeMethod(parent(), "RequestDisconnection", Q_ARG(QDBusObjectPath, device));
}

